language: go
go:
- 1.5
env:
- GO15VENDOREXPERIMENT=1
script:
- go test -v ./gluon-collector
- go test -v ./announced
- go test -v ./neighbour-discovery
- go test -v ./utils
- mkdir bin
- env GOOS=linux GOARCH=amd64 go build -o ./bin/gluon-collector ./gluon-collector
- env GOOS=linux GOARCH=386 go build -o ./bin/gluon-collector-linux-386 ./gluon-collector
- env GOOS=linux GOARCH=amd64 go build -o ./bin/neighbour-discovery ./neighbour-discovery
- env GOOS=linux GOARCH=386 go build -o ./bin/neighbour-discovery-linux-386 ./neighbour-discovery
deploy:
  provider: releases
  api_key:
    secure: EtC2N5fqMuAvvTSP9JSiKeIhQmqSrx1eOpDh4Ifw3VV6dqs0gYtrvMLreqoRUguGFd1hcNLXq49xKAIzfzuWdw+xH4yy3edw8Vwha3UPmTQ5rxUBABkx2U6ouFzRXnL93SW8zqqjO5R4oCvqKs5/mGhDCt10FNBZe6kmzkN1Et2KTHi/dewC6DGqlj2oieFJ+OKtrrOxv7OXoIX+U5CgBDxR1uZ86A1Vrm0d1/n43FhmBEJo88BVAggR0ZXtwDyJTJYPEaNLqEBt2ZzDI7SfVDZPYOy0U2ErfQW2GC1gbof8ZB+imVoCzKq3iHiGSZIHrqTKTNEHBSNjb4esD0quI2PWW1FdQygM/7NFOFWZ33RW1Hp9sHvbNOcmN/9jYG3XE6aFH1dwL9WmESj/wD1CMPWozV8Q4s8uRUjINVnbnBMdnkXMp17AFUHvQjaoRXr/CijEEFYOLpeczBOC0WMM7Pg0szecmG/Yc33zfBne6SQSDQWsslNdu67fOdJJRZTW+OCcipIMnFVv2OYkbbj7DsYJaEAxfjL0Qmvoz8mlth2sQlHv41J4Gle0TW3eii7pt6QbyLLBsScWiibyGBZL+Ua53SEXKGPyrs5dhpq1uDwJDfzoTZPfljX/F+evnZVPC9YQ9Y2ma2jXVsJZ9YzOcpo9AS0EKSjW5gdJHyc+CrI=
  file:
  - bin/gluon-collector
  - bin/gluon-collector-linux-386
  - bin/neighbour-discovery
  - bin/neighbour-discovery-linux-386
  on:
    repo: ffdo/node-informant
    tags: true
