receiver:
- type:  announced
  interface: "bat0"
  port: 21444

interval:
  statistics: 300
  nodeinfo: 1800

logger:
  level: "debug"

http:
  port: 8080
  #address: "[::]"

prometheus:
  namelabel: true
  sitecodelabel: true

meshviewer_version: 1
